### ISSUE TITLE
Misleading documentation?

### ISSUE THREAD

**Issue by ktnyt** [auth0-community/go-auth0#13]
In the "Client Credentials - HS256" section of the README, a comment suggests that "If you're secret is not base64 encoded, provide your key as a string" which is not true, as passing a "string" to the secret key provider will cause the jose verification routine to emit an "unsupported key type/format". This is because the type check inside of the jose verification routine will accept a "[]byte" but not a "string". This point should be clarified in the README.

P.S. It isn't much of a deal but the comment also includes a typo too: s/you're/your/.

**Comment by yageek** [comment]
Thanks for the feedback. By reading it again, it is obviously misleading. I'll change it ASAP.
