### ISSUE TITLE
Problem in README.md

### ISSUE THREAD

**Issue by ZhiguoZhang** [auth0-community/go-auth0#15]
hi, 

I am tring to use the example - "Using Gin and the Auth0 Authorization Extension", but I can't understand this line: 

    metadata, okMetadata := jwt.Claims().Get("app_metadata").(map[string]interface{})

because `jwt` was defined in `jwt, err := validator.ValidateRequest(c.Request)`, but it has not such function `Claims()` **Without parameter**.

Please help, thank you very much!

**Comment by yageek** [comment]
My bad :( The documentation is wrong. The usage of the squre JWT library implies some API changes for this part. I'll try to create a PR to correct it this week.

**Comment by yageek** [comment]
@ZhiguoZhang Could you confirm that the new information located here https://github.com/auth0-community/go-auth0/pull/16 is working you ? I added also some sample code inside the `example` directory.

**Comment by ZhiguoZhang** [comment]
@yageek Thank you for fixing and given the example. I tried, and hard part for me is that `loadPublicKey` part, the group extension only work if I attach the public key? what I did is like this:

    domain := config.GetConfig(domain)
	client := auth0.NewJWKClient(auth0.JWKClientOptions{URI: domain + config.GetConfig(json_path)})
	configuration := auth0.NewConfiguration(client, []string{config.GetConfig(audience)}, domain, jose.RS256)
	validator := auth0.NewValidator(configuration)

which means I jumped `LoadPublicKey` part, the `claims` then does not have `app_metadata`, I can't find the doc for auth0 about the public key part. I will continue search, thank you for the help.

**Comment by ZhiguoZhang** [comment]
I tried again, just found out my Auth0 need setup a Rule for receive app_metadata, and I have to use `domain`name as prefix for the `app_metadata`,  therefore direct use `claims["app_metadata"]` does not work for me, but in my `claims`there is data field like this: `https://somesubdomain.domain.some/app_metadata`
