### ISSUE TITLE
Error ignored when downloading keys 

### ISSUE THREAD

**Issue by alexbrand** [auth0-community/go-auth0#18]
The `GetKey` method of the `JWKClient` is ignoring the errors that can happen when downloading keys over the network. 

```
	if !exist {
		j.downloadKeys()
	}
```

`downloadKeys` returns an error:

```
func (j *JWKClient) downloadKeys() error 
```

**Comment by yageek** [comment]
Yes this is not a really good practice. The error should be returned one level up. I'm just creating a PR with a really small API change that should fix this issue.
