### ISSUE TITLE
Plans to be a full auth0 client?

### ISSUE THREAD

**Issue by progrium** [auth0-community/go-auth0#21]
I've been working on a Go client wrapper for some of the Auth0 auth and management APIs. Would it be a good idea to combine these?

**Comment by aaguiarz** [comment]
Hi

As Auth0 we don't have any current plans for investing in a Go SDK. That could change in the future, as everything ;)

@yageek as been contributing to this project, and he could have a better answer for you.

Regards,

Andres

**Comment by progrium** [comment]
Okay. I wasn't necessarily asking Auth0, unless "auth0-community" is not what it implies. So yes, I was directing this question at whoever actively maintains or puts code into this project. I assumed @yageek was at least a partial maintainer, and if not, I'm not sure why he'd have a better answer.

**Comment by yageek** [comment]
Hello,
sorry for the long non answer period. I just came back from holiday the last week and I had a lot of work to do.

I started the library because I needed it for one project and I had a very limited knowledge about the Auth0 platform. I have less time to contribute those days but I am not against a merge of efforts.

**Comment by bevanhunt** [comment]
I created a full Go Auth0 Client and also a Go JWT Verifier. https://github.com/apibillme/auth0 and https://github.com/apibillme/auth0-sdk - this thread inspired me - thanks!

**Comment by bishtawi** [comment]
There is another Go lib [here](https://github.com/go-auth0/auth0) which is currently being used by the auth0 Terraform module [here](https://github.com/alexkappa/terraform-provider-auth0).

**Comment by beardaway** [comment]
Hey there @bishtawi !

Thanks a lot for sharing that. Indeed we are working with Alex and official Auth0 module for Terraform should be released soon! Stay tuned!
