### ISSUE TITLE
Allow validating JWTs without a request object but directly with raw token string

### ISSUE THREAD

**Issue by ttjiaa** [auth0-community/go-auth0#33]
Currently most functions' logic starts with getting a request object, such as `func (v *JWTValidator) ValidateRequest(r *http.Request) (*jwt.JSONWebToken, error)`. In some cases, the raw token string could already be available, so it would be beneficial to have the option to call a function that deals directly with the raw token string, i.e. `ValidateJWT(raw string) (*jwt.JSONWebToken, error)`.

Additionally, in some cases it could make more sense if the logic does not deal with the request object at all, an example could be `func (j *JWKClient) GetSecret(r *http.Request) (interface{}, error)`. From the `JWKClient`'s perspective, only the `kid` is needed from the JWT token object, so having something like `func (j *JWKClient) GetSecret(token *JSONWebToken) (interface{}, error)` instead could be better, to avoid the duplication of logic for exacting the token from the raw token string.

**Comment by nickoneill** [comment]
+1

**Comment by beardaway** [comment]
I'm closing this issue for now. If anyone is still interested in it feel free to reopen it!
