### ISSUE TITLE
Pass audience as array to NewConfiguration instead of string

### ISSUE THREAD

**Issue by wvanteijlingen** [auth0-community/go-auth0#4]
Hi,

I've ran into a minor problem with the audience parameter in auth0.NewConfiguration. It's not possible for me to set multiple audiences because it expects a string and not a string array. I've fixed this locally by splitting on the audience string. In my case the separator is a space and I've implemented it as follows. 

const AUTH0_API_AUDIENCE = "x y z"

func NewConfiguration(provider SecretProvider, audience string, issuer string, method jose.SignatureAlgorithm) Configuration {
	var aud []string
	if audience != "" {
		aud = strings.Split(audience, " ")
	}
       ....
}

**Comment by yageek** [comment]
@wvanteijlingen A fix has been pushed. The API has changed: `audience` is an `[]string{}` now.
Feel free to reopen this issue if the bug appears again.

**Comment by wvanteijlingen** [comment]
@yageek works perfect, thanks.
